### ISSUE TITLE
Error in Default Funtion call

### ISSUE THREAD

**Issue by sada1993** [htoooth/Leaflet.ChineseTmsProviders#19]
`L.tileLayer.chinaProvider('TianDiTu.Normal.Map').addTo(map);` is throwing an error because `options` is empty, this works:

`L.tileLayer.chinaProvider('TianDiTu.Normal.Map',{}).addTo(map);`

**Comment by htoooth** [comment]
which is leaflet version ?

**Comment by htoooth** [comment]
ok, i fix it
