### ISSUE TITLE
how to use the provider in vue2leaflt

### ISSUE THREAD

**Issue by 0wenwu** [htoooth/Leaflet.ChineseTmsProviders#24]
I am now using vue2-leaflet, could you tell me use the provider in vue2leaflt. It confused me for a long time. Thank you!

**Comment by htoooth** [comment]
You can try  import this plugin after leaflet or vue2-leafet import.

**Comment by 0wenwu** [comment]
> You can try  import this plugin after leaflet or vue2-leafet import.

Thx for your reply, could you please give some demos? After importing the plugin, I still have no idea about how to use in my vue-based project
