### ISSUE TITLE
天地图的地址请升级下，在https 下是访问不了的。目前的地址不支持https协议。

### ISSUE THREAD

**Issue by houxianhu** [htoooth/Leaflet.ChineseTmsProviders#35]
天地图的地址请升级下，在https 下是访问不了的。目前的地址不支持https协议。

**Comment by htoooth** [comment]
支持的。没有指定协议，自适应。访问不了是因为 访问流量太大了。限流了。

@houxianhu

**Comment by houxianhu** [comment]
> 支持的。没有指定协议，自适应。访问不了是因为 访问流量太大了。限流了。
> 
> @houxianhu

https://t{s}.tianditu.gov.cn 官方支持的地址

**Comment by houxianhu** [comment]
@htoooth  

https://t{s}.tianditu.gov.cn 官方支持的地址

**Comment by houxianhu** [comment]
@htoooth  

//t{s}.tianditu.gov.cn 官方支持的地址

**Comment by htoooth** [comment]
@houxianhu 

thx
