### ISSUE TITLE
放在Android assets文件中WebView加载不出

### ISSUE THREAD

**Issue by ccclao** [htoooth/Leaflet.ChineseTmsProviders#38]
天地图，高德，百度，OSM都不能加载，只有MapBox能正常加载

**Comment by Vanish136** [comment]
@ccclao 老哥 请问你是怎么解决的？我也遇到这个问题了

**Comment by ccclao** [comment]
那些都是链接错误的，看下这博文https://blog.csdn.net/csdn9228/article/details/110915265

**Comment by Vanish136** [comment]
谢谢 我搞定了
