### ISSUE TITLE
会增加百度地图吗？

### ISSUE THREAD

**Issue by yangyangcv** [htoooth/Leaflet.ChineseTmsProviders#4]
纯新手好奇为啥没有百度，可能是百度不提供TMS？
另外，似乎天地图官网的在线地图更新得比使用API获取的要新？我公司旁边的一个大楼，天地图官网在线地图里能看到已经建好了，用这个api看到的还是一片空地。。。

**Comment by seifer08ms** [comment]
@yangyangcv ，百度瓦片规则不太一样。另外图商的API底图肯定更新的是最及时的，这是产品的策略，迫使别人用他们的API。

**Comment by htoooth** [comment]
@seifer08ms 兄弟你在哪工作啊？

**Comment by seifer08ms** [comment]
@htoooth ，山东一家房地产数据的小公司。

**Comment by liyu272173673** [comment]
听说百度不发布地图，他们数据是”四维图新”买来的 。
