### ISSUE TITLE
可以增加支持腾讯地图吗？

### ISSUE THREAD

**Issue by LwkCoder** [htoooth/Leaflet.ChineseTmsProviders#44]
腾讯地图的切片方式好像和天地图、高德这些不一样，不知道怎么在这个插件的基础上进行扩展，希望作者能帮帮忙
矢量图Url：https://rt{s}.map.gtimg.com/realtimerender?z={z}&x={x}&y={y}&type=vector&style=2
卫星图Url：http://p{s}.map.gtimg.com/sateTiles/{z}/{r}/{c}/{x}_{y}.jpg
地形图Url：http://p{s}.map.gtimg.com/demTiles/{z}/{r}/{c}/{x}_{y}.jpg

**Comment by huangsinan** [comment]
矢量图在y前面加个负号就行

**Comment by a309492165** [comment]
这个加了负号可以出来，但是点位置还是差了不少
