### ISSUE TITLE
百度地图瓦片地图地址失效，求更

### ISSUE THREAD

**Issue by kuole-o** [htoooth/Leaflet.ChineseTmsProviders#46]
http://htoooth.github.io/Leaflet.ChineseTmsProviders/examples/indexBaidu.html

百度地图瓦片地图，好像失效了

**Comment by daolanfler** [comment]
右上角可以选择图层，目前还没有失效。

**Comment by htoooth** [comment]
The link is fine. You must chose a layer. @kuole-o
