### ISSUE TITLE
在移动端加载不显示问题 

### ISSUE THREAD

**Issue by Childrenlovebaths** [htoooth/Leaflet.ChineseTmsProviders#50]
在移动端加载的时候是不显示的, 是有其他的配置还是不支持吗

**Comment by htoooth** [comment]
@Childrenlovebaths  TianDiTu map need a key. You must apply a key for yourself.

**Comment by Childrenlovebaths** [comment]
我是有申请密钥的` //天地图
    // L.tileLayer
    //   .chinaProvider("TianDiTu.Satellite.Map", {
    //     key: localStorage.tianditukey,
    //   })
    //   .addTo(this.map);`

**Comment by Childrenlovebaths** [comment]
很高兴您能回答我的问题， 我是在web段可以显示  在h5端不显示 ，这个是我的代码您看一下有没有什么问题                                ` L.tileLayer
      .chinaProvider("TianDiTu.Satellite.Map", {
        key: localStorage.tianditukey,
      })
      .addTo(this.map);`

**Comment by mlzk** [comment]
> 
源文件没有标明使用的协议是http还是https，自己加上http前缀就行了


> 很高兴您能回答我的问题， 我是在web段可以显示 在h5端不显示 ，这个是我的代码您看一下有没有什么问题 ` L.tileLayer .chinaProvider("TianDiTu.Satellite.Map", { key: localStorage.tianditukey, }) .addTo(this.map);`

**Comment by Childrenlovebaths** [comment]
感谢
