### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by sunguoxing0628** [htoooth/Leaflet.ChineseTmsProviders#9]
在[`https://www.npmjs.com/`](https://www.npmjs.com/search?q=Leaflet.ChineseTmsProviders)只能查到2年前`1.0.22`版本，不是最新。

**Comment by htoooth** [comment]
@sunguoxing0628  那个不是我放的，我自己来放一个吧

**Comment by htoooth** [comment]
@sunguoxing0628 
已经发了一个包

```bash
npm i leaflet.chinatmsproviders
```
